//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST_CRUD_WCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingredient_images
    {
        public int id { get; set; }
        public Nullable<int> ingredient_id { get; set; }
        public string image { get; set; }
    }
}
