//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REST_CRUD_WCF.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class coffee_room_Entities : DbContext
    {
        public coffee_room_Entities()
            : base("name=coffee_room_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dish> dishes { get; set; }
        public virtual DbSet<dish_images> dish_images { get; set; }
        public virtual DbSet<ingredient_images> ingredient_images { get; set; }
        public virtual DbSet<ingredient> ingredients { get; set; }
        public virtual DbSet<recipe> recipes { get; set; }
    }
}
